# Generated by Django 5.0.6 on 2024-12-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_email_alter_user_username'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company the user is associated with if they are an admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='Company.company'),
        ),
    ]
