# Generated by Django 5.0.6 on 2024-12-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
