# Generated by Django 5.0.6 on 2024-12-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
