# Generated by Django 5.0.6 on 2024-12-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0006_remove_rolerequest_approved_rolerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Cancellation_policy', models.CharField(max_length=600)),
                ('Guest_policy', models.CharField(max_length=600)),
                ('desk', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='desk/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Cancellation_policy', models.CharField(max_length=600)),
                ('Guest_policy', models.CharField(max_length=600)),
                ('capacity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='offices/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='room_images/')),
                ('amenities', models.ManyToManyField(to='Company.officeamenities')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Office.timeslot')),
            ],
        ),
    ]
