# Generated by Django 5.0.6 on 2024-12-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='date',
        ),
        migrations.RemoveField(
            model_name='office',
            name='date',
        ),
    ]
