# Generated by Django 5.0.6 on 2024-12-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0003_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slot',
        ),
    ]
