# Generated by Django 5.0.6 on 2024-12-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0004_remove_room_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Office.room'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
