# Generated by Django 5.0.6 on 2024-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='ratings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
