# Generated by Django 5.0.6 on 2024-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_is_visible_alter_company_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeamenities',
            name='office_post',
        ),
        migrations.AddField(
            model_name='company',
            name='amenites',
            field=models.ManyToManyField(to='Company.officeamenities'),
        ),
    ]
