# Generated by Django 5.0.6 on 2024-12-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_company'),
        ('Company', '0003_remove_officeamenities_office_post_company_amenites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to='Account.user'),
        ),
    ]
