# Generated by Django 5.0.6 on 2024-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_rolerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(default='company_admin', max_length=20),
        ),
    ]
