# Generated by Django 5.0.6 on 2024-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_rolerequest_requested_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolerequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
