# Generated by Django 5.0.6 on 2024-12-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_remove_rolerequest_approved_rolerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('embed_map_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.location'),
        ),
    ]
