# Generated by Django 5.0.6 on 2024-12-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_location_alter_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
